### ISSUE TITLE
Error: SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by Farhadesfandiar** [monero-integrations/monerophp#125]
I use php 7.4, apache2 and run ./monerod in testnet. When I try to send my curl request to the monero on my localhost, I see this error.
When I disable ssl certificate, I get the error :
Error: SSL: unable to obtain common name from peer certificate

**Comment by serhack** [comment]
> I see this error.

I can not see the error, unless you meant "Error: SSL unable to obtain common name from peer certificate". You should connect to Monerod, using `SSL` option set to `true`. I would not suggest you to disable [`CURLOPT_SSL_VERIFYPEER `](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html).

**Comment by henkjanh14** [comment]
Have this same problem.
Running Nginx server PHP7.4-fpm 
Ran monerod with command ./monerod --testnet --rpc-ssl-allow-any-cert --detach  <<tried the allow any cert arg
When visiting example on webserver I got this error:
`Fatal error: Uncaught RuntimeException: Unable to connect to https://127.0.0.1:28081/ Error: SSL certificate problem: self signed certificate in /var/www/public/src/jsonRPCClient.php:140 Stack trace: #0 /var/www/public/src/jsonRPCClient.php(80): MoneroIntegrations\MoneroPhp\jsonRPCClient->getResponse() #1 /var/www/public/src/daemonRPC.php(112): MoneroIntegrations\MoneroPhp\jsonRPCClient->_run() #2 /var/www/public/src/daemonRPC.php(129): MoneroIntegrations\MoneroPhp\daemonRPC->_run() #3 /var/www/public/example.php(16): MoneroIntegrations\MoneroPhp\daemonRPC->getblockcount() #4 {main} thrown in /var/www/public/src/jsonRPCClient.php on line 140`

It's on a private ubuntu testing environment. 
Does the certificate problem occur because the webserver doesn't have a SSL certificate? (because its private)

**Comment by recanman** [comment]
@serhack can you close this?
