### ISSUE TITLE
Generating a Monero address

### ISSUE THREAD

**Issue by serhack** [monero-integrations/monerophp#18]
Generating a Monero address by PHP library!

- [x] bigint library for generating seed

- [x] base58 library

- [x] Monero functions for generating address
- [ ] Monero "Config"  (https://github.com/mymonero/mymonero-core-js/blob/master/monero_utils/monero_config.js)

Should we create a repo that will contain the library for a general cryptocoin based on cryptonote algorithm?

**Comment by sneurlax** [comment]
re: base58 library, see #27! :)

**Comment by cryptochangements34** [comment]
#28 proposes to optionally uses gmp for precision math (big int) and #29 encodes mainnet monero addresses utilizing #27

**Comment by cryptochangements34** [comment]
I don't really think a config file is (at least currently) necessary. I also think that because this project was funded by the Monero community it should stay strictly for Monero. If somebody else wants to fork this repo it should only require a few simple modifications so we can just leave them to do that themselves instead of dealing with different configurations for the different changes/tweaks that other Monero/Cryptonote forks made. If you agree then I think this issue can be closed.

**Comment by serhack** [comment]
Agree.
